version: 0.0  
os: linux  
files:  
  - source: /  
    destination: /root/ROR
permissions:
  - object: /root/ROR/ROR.sh
    mode: 777
    owner: root
    type:
      - file  

hooks:
  BeforeInstall:  
    - location: BeforeInstall.sh   
      runas: root 
      

  ApplicationStart:  
    - location: ApplicationStart.sh
#       runas: root 
